baseURL = "https://www.bastard-uncle.com/"
languageCode = "en-uk"
title = "Bastard Uncle"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = ""
enableEmoji = true
publishDir = "public"
#disqusShortname = "your-shortname-here"
googleAnalytics = "UA-46298735-2"

[params]
  logo = "/images/logo.png"
  description ="All best best noisy, messy, fun toys nobody else will buy them"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "The Bastard Uncle"
  thumbnail = "/images/author.png"
  description = "Honestly, I'm not that much of a bastard"

[params.index]
  picture = "/images/author.png"
  title = "Bastard Uncle.com"
  subtitle = "All the noisy and messy toys which are too much fun for parents to give them"
  mdtext = '''
Have a browse though the various categories
'''
  alertbar = false

[params.social]
  twitter = "<username>"
  instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "Toys"
    weight = 100
    identifier = "toys"
    url = "/blog"
